version: '3.8'
services:
  app:
    image: bluerally/bluerally-be:latest
    container_name: blue-rally-app
    restart: always
    expose:
      - "8000"
    env_file:
      - .env
    volumes:
      - /home/ec2-user/logs:/app/logs
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
networks:
  bluerally-network:
    external: true
