name: Deploy to AWS

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install poetry
        poetry install

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      run: |
        GIT_TAG=${GITHUB_REF#refs/tags/}
        docker build -t bluerally/bluerally-be:$GIT_TAG .
        docker push bluerally/bluerally-be:$GIT_TAG

    - name: Zip the build
      run: zip -r blue-rally-build.zip .

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Create metadata file and upload to S3
      run: |
        GIT_TAG=${GITHUB_REF#refs/tags/}
        echo $GIT_TAG > metadata.txt
        aws s3 cp metadata.txt s3://blue-rally/metadata.txt

    - name: Upload to Amazon S3
      run: aws s3 cp blue-rally-build.zip s3://blue-rally/blue-rally-build.zip

    - name: Trigger AWS CodeDeploy
      run: |
        aws deploy create-deployment \
        --application-name blue-rally-deploy \
        --deployment-config-name CodeDeployDefault.OneAtATime \
        --deployment-group-name blue-rally-deploy-group \
        --s3-location bucket=blue-rally,bundleType=zip,key=blue-rally-build.zip
